baseURL: 'https://philipptrashman.github.io/bbs2-wahlprogramm/'
title: 'Deutsche Wahlprogramme 2025'
theme: 'paper-mod'

enableInlineShortcodes: true
enableEmoji: true
mainsections: ["parties"]

defaultContentLanguage: 'de'

languages:
  de:
    languageName: "Deutsch"
    weight: 1
    menu:
      main:
        - name: Home
          url: /
          weight: 1
        - name: Parteien
          url: /parties
          weight: 5

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  defaultTheme: auto
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: true
  editPost:
    URL: "https://google.com/"
    Text: "Suggest Changes" # edit text
    appendFilePath: true

  assets:
    disableHLJS: true
  
  menu-style: "side-navigation"

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
