baseURL: 'https://philipptrashman.github.io/bbs2-wahlprogramm/'
title: 'Deutsche Wahlprogramme 2025'
theme: 'hugo-theme-techdoc'

enableInlineShortcodes: true
enableEmoji: true
mainsections: ["parties"]

defaultContentLanguage: 'de'

languages:
  de:
    languageName: Deutsch
    weight: 1
    menu:
      main:
        - identifier: home
          name: Home
          url: /
          weight: 1
        - identifier: parties
          name: Parteien
          url: /parties
          weight: 5

params:
  custom_background_color: null
  custom_font_color: null
  menu_style: slide-menu
  menu_exclusions: 
    - archives,
    - archive
    - tags
    - blog
    - entry
    - post
    - posts

  assets:
    disableHLJS: true


markup:
  tableOfContents:
    startLevel: 2
    endLevel: 3
      
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
